sudo: required
dist: trusty

language: node_js

node_js:
  - "6"

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm get prefix
  - npm install -g firebase-tools
  - npm set progress=false
  - npm install

before_script:
# cache:
#   bundler: true
#   directories:
#   - node_modules # NPM packages

script:
  - sudo ./build/deploy.sh
  - npm run lint
  - npm run test
  - NODE_ENV=production npm run deploy

after_success:
  - npm run codecov

notifications:
  email:
    on_failure: change
    on_success: change
