sudo: required
dist: trusty

language: node_js

node_js:
  - "6"

install:
  - npm get prefix
  - npm install -g firebase-tools
  - npm set progress=false
  - npm install

cache:
  bundler: true
  directories:
  - node_modules # NPM packages

script:
  - npm run lint
  - npm run test
  - NODE_ENV=production npm run deploy
  - npm run fb

after_success:
  - npm run codecov

notifications:
  email:
    on_failure: change
    on_success: change
