language: node_js

node_js:
- "6"

sudo: false

branches:
  only:
    - master

script:
  - npm run lint
  - npm run test
  - NODE_ENV=production npm run deploy

cache:
  bundler: true
  directories:
  - node_modules # NPM packages

deploy:
  skip_cleanup: true
  provider: heroku
  api_key:
    secure: $HEROKU_KEY
  app: $HEROKU_APP

install:
  - npm install

after_success:
  - bash <(curl -s https://codecov.io/bash)
  # - npm run codecov
